### ISSUE TITLE
无法上传且报错为乱码

### ISSUE THREAD

**Issue by musnows** [ygxbnet/lsky-upload#1]
如题，typora版本`0.9.98`，不管是尝试拷贝上传，还是点击`验证上传选项`都会报错。yml已经配置且程序路径没有中文

```
D:\Program Files\lsky-upd\lsky-upload.exe
```

另外，README的图片看不到了。建议作者将截图直接拷贝到仓库目录下，毕竟只有一张（避免失效）

![image](https://user-images.githubusercontent.com/87506951/236590759-0deb23bd-0739-4ea7-8647-9da014be77a9.png)

**Comment by musnows** [comment]
我猜测是空格的问题，没想到还真是。将路径修改了一下，就没有问题了。建议作者在README里面加上说明
```
D:\lsky-upd\lsky-upload.exe
```

>我更换到您这个项目的原因是picgo+typora会出现卡上传的问题 https://github.com/Molunerfinn/PicGo/issues/1060 
>
>在我的电脑上，只要picgo已经启动了，typora关闭后重开，就一定会出现这个问题（新版的typora+picgo一样会有，玄学）
>只有将picgo和typora同时关闭，下次开启的时候，让typora启动picgo，或者两个一起启动（相当于typora不能独立关闭），才能正常上传🤣

不知道您这个能否解决此问题。用几天看看。感谢开源！

**Comment by ygxbnet** [comment]
非常感谢提出问题！

- 关于 README 的截图，我明天来把它上传到仓库中
- 关于路径的问题，我估计是 typora 的问题，明天来测试一下，如果是的话我会在文档中加以说明
- 关于 PicGo，我开发此程序是因为 PicGo 对我的需求来说太过于复杂了，所以就想写一个简单一点的程序。也正因为如此，我很久没有用过 PicGo 了，所以可能不太能解决这个问题

最后再一次感谢您使用本项目并提出问题
PS：原本是自己做着好玩的东西，没想到真的还有人用 (≧∇≦)/

**Comment by musnows** [comment]
> 非常感谢提出问题！
> 
> * 关于 README 的截图，我明天来把它上传到仓库中
> * 关于路径的问题，我估计是 typora 的问题，明天来测试一下，如果是的话我会在文档中加以说明
> * 关于 PicGo，我开发此程序是因为 PicGo 对我的需求来说太过于复杂了，所以就想写一个简单一点的程序。也正因为如此，我很久没有用过 PicGo 了，所以可能不太能解决这个问题
> 
> 最后再一次感谢您使用本项目并提出问题 PS：原本是自己做着好玩的东西，没想到真的还有人用 (≧∇≦)/

没事没事，我只是提了一下picgo的问题，并没有说要您帮忙解决这个问题🤣。昨天用了您的程序，目前看来是没有类似picgo卡上传的问题的。再次感谢开源。

> 要是能增加lsky上传的存储策略选项就更好了（咳咳，虽然我用不上）

**Comment by ygxbnet** [comment]
教程已经更新了，只用把带空格的路径用 `"` 括起来就可以了
[教程](https://github.com/YGXB-net/lsky-upload#%E4%B8%8B%E8%BD%BD--%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)

**Comment by musnows** [comment]
> 教程已经更新了，只用把带空格的路径用 `"` 括起来就可以了 [教程](https://github.com/YGXB-net/lsky-upload#%E4%B8%8B%E8%BD%BD--%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)

好的，请问您知道如下报错是为什么吗？我尝试在deepin上面构建代码

```
mothra@mothra-PC: ~/Downloads/lsky-upload$ go build
internal/config/config.go:4:2: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)
```

百度过了几个办法，并不管用

```
mothra@mothra-PC:~/Downloads/lsky-upload$ go env -w GO111MODULE=off
mothra@mothra-PC:~/Downloads/lsky-upload$ go install
main.go:7:2: cannot find package "github.com/tidwall/gjson" in any of:
        /usr/lib/go-1.15/src/github.com/tidwall/gjson (from $GOROOT)
        /home/mothra/go/src/github.com/tidwall/gjson (from $GOPATH)
main.go:9:2: cannot find package "lsky-upload/internal/config" in any of:
        /usr/lib/go-1.15/src/lsky-upload/internal/config (from $GOROOT)
        /home/mothra/go/src/lsky-upload/internal/config (from $GOPATH)
main.go:10:2: cannot find package "lsky-upload/internal/httpapi" in any of:
        /usr/lib/go-1.15/src/lsky-upload/internal/httpapi (from $GOROOT)
        /home/mothra/go/src/lsky-upload/internal/httpapi (from $GOPATH)
main.go:11:2: cannot find package "lsky-upload/internal/utils" in any of:
        /usr/lib/go-1.15/src/lsky-upload/internal/utils (from $GOROOT)
        /home/mothra/go/src/lsky-upload/internal/utils (from $GOPATH)
```

**Comment by musnows** [comment]
> > 教程已经更新了，只用把带空格的路径用 `"` 括起来就可以了 [教程](https://github.com/YGXB-net/lsky-upload#%E4%B8%8B%E8%BD%BD--%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95)
> 
> 好的，请问您知道如下报错是为什么吗？我尝试在deepin上面构建代码
> 
> ```
> mothra@mothra-PC: ~/Downloads/lsky-upload$ go build
> internal/config/config.go:4:2: package embed is not in GOROOT (/usr/lib/go-1.15/src/embed)
> ```
> 
> 百度过了几个办法，并不管用
> 
> ```
> mothra@mothra-PC:~/Downloads/lsky-upload$ go env -w GO111MODULE=off
> mothra@mothra-PC:~/Downloads/lsky-upload$ go install
> main.go:7:2: cannot find package "github.com/tidwall/gjson" in any of:
>         /usr/lib/go-1.15/src/github.com/tidwall/gjson (from $GOROOT)
>         /home/mothra/go/src/github.com/tidwall/gjson (from $GOPATH)
> main.go:9:2: cannot find package "lsky-upload/internal/config" in any of:
>         /usr/lib/go-1.15/src/lsky-upload/internal/config (from $GOROOT)
>         /home/mothra/go/src/lsky-upload/internal/config (from $GOPATH)
> main.go:10:2: cannot find package "lsky-upload/internal/httpapi" in any of:
>         /usr/lib/go-1.15/src/lsky-upload/internal/httpapi (from $GOROOT)
>         /home/mothra/go/src/lsky-upload/internal/httpapi (from $GOPATH)
> main.go:11:2: cannot find package "lsky-upload/internal/utils" in any of:
>         /usr/lib/go-1.15/src/lsky-upload/internal/utils (from $GOROOT)
>         /home/mothra/go/src/lsky-upload/internal/utils (from $GOPATH)
> ```

解决了！我之前的go版本是1.15，太低了，升级到最新版本1.20.4就ok了🤣

https://blog.csdn.net/qq_35633748/article/details/129436192

![image](https://user-images.githubusercontent.com/87506951/236657314-6dabe897-8f26-4dbd-b10f-89aa2afb32c5.png)

**Comment by ygxbnet** [comment]
对是版本低了，我使用的golang是1.20版本的
