### ISSUE TITLE
mac os 上传报错

### ISSUE THREAD

**Issue by huajien** [ygxbnet/lsky-upload#14]
日志
```
2024/05/18 19:09:30
 [[❗上传图片错误： Post "https://pro.******.com/api/v1/upload": tls: failed to verify certificate: x509: “*.&&&&&.com” certificate is revoked]]
```

<img width="510" alt="image" src="https://github.com/ygxbnet/lsky-upload/assets/75553778/8e523108-748e-462b-b467-09f258685ee0">

**Comment by ygxbnet** [comment]
这个问题可能是服务器证书的问题，您可以先查看一下服务器的证书是否过期

**Comment by huajien** [comment]
> 这个问题可能是服务器证书的问题，您可以先查看一下服务器的证书是否过期

<img width="320" alt="image" src="https://github.com/ygxbnet/lsky-upload/assets/75553778/f3473524-43e4-4986-b1b6-00ebf933834f">

证书是有效的windows端可以上传mac 端就报错

是因为https的问题吗

**Comment by ygxbnet** [comment]
我查了一下，这个好像是一个 MacOS 证书 x509 的问题。

这个问题在 https://github.com/golang/go/issues/51991 被讨论过，但好像并没有一个具体的解决方法，我明天会发布一个版本来跳过证书验证，可以改善这个问题

**Comment by ygxbnet** [comment]
OK，新版已发布：https://github.com/ygxbnet/lsky-upload/releases/tag/v0.4.2

- 先下载更新软件
- 再在配置文件中添加以下配置

```yaml
insecure-skip-verify: true
```
